### ISSUE TITLE
Save availability to use for multiple events

### ISSUE THREAD

**Issue by rpophessagr** [GRA0007/crab.fit#114]
It can be frustrating to fill out the same availability from my schedule for different events. 
It would be useful to be able to save my availability grid, and apply it to new events.
Thanks for considering, and for making a great app!

**Comment by GRA0007** [comment]
Ooh this is an interesting idea, I'll add it to my list, thanks for the suggestion!

**Comment by altsalt** [comment]
Love this idea! As a use case, I often set up a quarterly availability poll with my free timeslots that I can send to others to fill out which ones within those periods. This feature request is a bit of an inverse, in that I could apply those free slots to any poll and manually de-select the ones that have since filled.

**Comment by loleg** [comment]
I also think it would be also great to have availability coming out of public calendars. [iCalendar](https://en.wikipedia.org/wiki/ICalendar) (ics) support through something like https://github.com/cwlsn/ics-to-json might be the easiest option, though it's likely that for maximum usability you'd also want to integrate popular APIs (Google, Outlook, Apple).

**Comment by loleg** [comment]
Thanks - awesome!
