### ISSUE TITLE
Warn when selecting dates in the past

### ISSUE THREAD

**Issue by peterkaminski** [GRA0007/crab.fit#141]
**Is your feature request related to a problem? Please describe.**

During a moment of cognitive overload, I created a poll that had dates two weeks in the past, rather than one week in the future, as I wanted.

I can't imagine a good use case for polling for days in the past, so I think that should be disallowed in the UI.

**Describe the solution you'd like**

When presented with the calendar interface for "What dates might work?" and "Specific dates", the previous month arrow would be grayed out and disabled. Days in the past in the current month would be grayed out and disabled.

**Describe alternatives you've considered**

None.

**Additional context**

In this case, I created a new poll.  I wished that I could delete the old poll, see #140.

**Comment by GRA0007** [comment]
Thanks for your report @peterkaminski, and sorry for the late reply! As I touched on in #140, I'm not worried about unused events, as they're deleted automatically after 3 months of inactivity, and to enable deletion would require a user account system that is out of scope for this project.

As for selecting dates in the past, there may be a valid reason, so I don't want to disable that functionality, however I'm going to rename this issue so it's about _warning_ a user that they've selected dates in the past before they submit, in case it wasn't intentional.
