### ISSUE TITLE
Dependency on Google

### ISSUE THREAD

**Issue by Amustache** [GRA0007/crab.fit#143]
Would it be possible to have alternative to the Google Cloud Platform™?

Thank you for your time!

**Comment by kimimaru4000** [comment]
+1 to this. I would love to self-host without having to rely on Google to use this.

**Comment by GRA0007** [comment]
Currently the backend is closely integrated with Google datastore, but I will look into abstracting that logic so it can be configured for any database.

I'll also look into providing some more advanced documentation for self-hosting Crab Fit after I make those changes. Thanks for the request.

**Comment by desinox** [comment]
++ would also love a version without google cloud

**Comment by mayel** [comment]
> Would it be possible to have alternative to the Google Cloud Platform™?

+1 

> I'll also look into providing some more advanced documentation for self-hosting

A Dockerfile (and ideally prebuilding images in CI) and docker-compose would be really handy!

**Comment by TuringTux** [comment]
@GRA0007 Do you need any assistance with this? I would really love to self host Crab Fit and if there is a way I can help to make it possible, I'll be happy to provide assistance.

I've never worked with Crab Fit before though, so I am not sure if I'd be more of a help or a hindrance. 😅

**Comment by loleg** [comment]
There are about [10 places](https://github.com/GRA0007/crab.fit/search?l=JavaScript&q=datastore) in the code where this would need to happen. I don't see any particularly sophisticated queries, so pretty much any drop-in KVS or ORM should work. I'd recommend [Sequelize](https://sequelize.org/) for this project.

**Comment by TuringTux** [comment]
We'd then probably also need to change some configuration for deployment on arbitrary URLs, e.g. the CORS headers: https://github.com/GRA0007/crab.fit/blob/main/crabfit-backend/index.js#L25

Sequelize does look incredibly cool.

Do I see this right that with Google datastore, the data types (e.g. something like Event) are never explicitly defined? So that would probably be something one had to model explicitly.

**Comment by TuringTux** [comment]
So, I've just started searching what data types this application has: So far, I've found three (`Event`, `Person` and `Stats`) and it seems like there are no other types than those three.

I have created a [`types.js`](https://github.com/TuringTux/crab.fit/blob/main/crabfit-backend/model/types.js) file in my fork where I'll start to model them with Sequelize. If anyone wants to join the efforts, please feel free to message me, we can work on the fork together :)

The efforts to specify the model are probably also related to #230...

**Comment by TuringTux** [comment]
Or maybe scrap all the above: @GRA0007 just mentioned that https://keyv.js.org/ and it seems pretty much exactly like what I was trying to do manually.

brb, reading the docs...

**Comment by mayel** [comment]
@TuringTux something like https://www.npmjs.com/package/@nano-sql/core ? (this is not a recommendation, I haven't used it before)

**Comment by TuringTux** [comment]
@mayel Yes, something like this. Consider me genuinely surprised 😀 

For now, I've nevertheless decided to create an own abstraction layer first and change all occurrences in the code to use it, which would then look e.g. like [this](https://github.com/TuringTux/crab.fit/blob/main/crabfit-backend/routes/createEvent.js).

Basically, we'd then have `Event.get` or `Event.create` to get existing or create new events, respectively and `event.save` (to be called on an existing event instance) to update that event in the database. As soon as I've fleshed out that API, I will probably document it, clean up the commits etc.

Then, I'll start choosing a (or multiple) fitting drivers (so maybe nano-sql, or Sequelize, or firestore, or keyv, or ...) and start working on the concrete implementations.

**Comment by TuringTux** [comment]
Do any of you know how to get the full key out of Datastore? My code basically looks like this:

```js
const entityData = { 
  name: name.trim(), 
  password
  // ...
}

const entity = {
  key: datastore.key("Person"),
  data: entityData
}
await datastore.insert(entity)
```

I create an entity and insert it with an incomplete key, to let Datastore generate an id for me. How do I find out which id has been generated? Does `insert` return anything useful?

(I would test it, but I currently don't have access to a datastore instance)

**Comment by TuringTux** [comment]
Status report: A lot of functionality has been moved to `drivers/datastore.js` already. What still needs to be done:

* `taskCleanup.js` and `taskRemoveOrphans.js` still use datastore calls that are not yet in the abstraction layer. I haven't entirely decided how to implement this: Basically, I could implement a `Event.findOld` method similar to `Event.get`, but as more or less the only thing I want to do with those events is deleting them, it might be efficient to skip the step of first creating object representations of all thos events.
* There still is a `findEvent` method that finds an event with a given id using a query. I wonder if that could be replaced by using `Event.get` (which relies on `datastore.get`, instead of a query). However, maybe that is not possible (`findEvent` is currently only used when creating events, to check if an event with a certain id exists).
* The abstractions should be tested by someone who has access to a Google Cloud Datastore. Ideally, everything still works exactly as before.

**Comment by TuringTux** [comment]
Updated status report: While the above still holds true, it should now be possible to **implement you own storage driver**!

To do so, you have to create a new file in [`model/drivers`](https://github.com/TuringTux/crab.fit/tree/introduce-abstraction-layer/crabfit-backend/model/drivers) implementing the `BaseEvent`, `BasePerson` and `BaseStat` classes from [`model/base.js`](https://github.com/TuringTux/crab.fit/blob/introduce-abstraction-layer/crabfit-backend/model/base.js).

Then, you can change which driver to use in [`model/index.js`](https://github.com/TuringTux/crab.fit/blob/introduce-abstraction-layer/crabfit-backend/model/index.js).

**Comment by GRA0007** [comment]
Thanks everyone who's been following along with this, and thanks especially to @TuringTux who put in the effort to try and make it a reality ⭐ 

I've been working on rewriting the API in Rust (#257) and the frontend in Next.js (#259), which will bring the option to choose a custom database when self-deploying Crab Fit. Full documentation on spinning up your own instance is coming soon!

As for addressing _this_ issue, I would like to move off Google Datastore, however finding an alternative database that is fast and costs a similar amount is tricky. Because of this, the production site at https://crab.fit will likely continue to use Google Datastore for the time being until I can find a suitable replacement.

**Comment by GRA0007** [comment]
Update: I've released an initial guide on self-hosting here: https://github.com/GRA0007/crab.fit/wiki/Self%E2%80%90hosting

Please let me know if it's missing any info!

**Comment by mayel** [comment]
The way you describe licensing at the top applies to AGPL rather than GPL, so you may want to consider relicensing as AGPL?

**Comment by GRA0007** [comment]
@mayel thanks for pointing that out! I didn't realise the difference, but I'm honestly not too worried about that case, so I've edited the wiki page :)
